# Generated by Django 3.1.3 on 2020-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_address', models.TextField()),
                ('loc_x_coor', models.CharField(max_length=10)),
                ('loc_y_coor', models.CharField(max_length=10)),
            ],
        ),
    ]
